// Generated by gencpp from file demo_custom_msg/custom_msg.msg
// DO NOT EDIT!


#ifndef DEMO_CUSTOM_MSG_MESSAGE_CUSTOM_MSG_H
#define DEMO_CUSTOM_MSG_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_custom_msg
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : name()
    , number(0)  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::demo_custom_msg::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_custom_msg::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::demo_custom_msg::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::demo_custom_msg::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::demo_custom_msg::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_custom_msg::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_custom_msg::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo_custom_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'demo_custom_msg': ['/home/ammmy/Desktop/tutorial_ws/src/demo_custom_msg/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_custom_msg::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_custom_msg::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_custom_msg::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b67238d624be977c27607899c0cdedf";
  }

  static const char* value(const ::demo_custom_msg::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b67238d624be977ULL;
  static const uint64_t static_value2 = 0xc27607899c0cdedfULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_custom_msg/custom_msg";
  }

  static const char* value(const ::demo_custom_msg::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
int32 number\n\
";
  }

  static const char* value(const ::demo_custom_msg::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_custom_msg::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_custom_msg::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_CUSTOM_MSG_MESSAGE_CUSTOM_MSG_H
