// Generated by gencpp from file demo_service_cpp/simple_srvRequest.msg
// DO NOT EDIT!


#ifndef DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRVREQUEST_H
#define DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_service_cpp
{
template <class ContainerAllocator>
struct simple_srvRequest_
{
  typedef simple_srvRequest_<ContainerAllocator> Type;

  simple_srvRequest_()
    : in()  {
    }
  simple_srvRequest_(const ContainerAllocator& _alloc)
    : in(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _in_type;
  _in_type in;





  typedef boost::shared_ptr< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simple_srvRequest_

typedef ::demo_service_cpp::simple_srvRequest_<std::allocator<void> > simple_srvRequest;

typedef boost::shared_ptr< ::demo_service_cpp::simple_srvRequest > simple_srvRequestPtr;
typedef boost::shared_ptr< ::demo_service_cpp::simple_srvRequest const> simple_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo_service_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2718218ecd3037e7050a0e8416c50c33";
  }

  static const char* value(const ::demo_service_cpp::simple_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2718218ecd3037e7ULL;
  static const uint64_t static_value2 = 0x050a0e8416c50c33ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_service_cpp/simple_srvRequest";
  }

  static const char* value(const ::demo_service_cpp::simple_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string in\n\
";
  }

  static const char* value(const ::demo_service_cpp::simple_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.in);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_service_cpp::simple_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_service_cpp::simple_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "in: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.in);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRVREQUEST_H
