// Generated by gencpp from file demo_service_cpp/simple_srvResponse.msg
// DO NOT EDIT!


#ifndef DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRVRESPONSE_H
#define DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_service_cpp
{
template <class ContainerAllocator>
struct simple_srvResponse_
{
  typedef simple_srvResponse_<ContainerAllocator> Type;

  simple_srvResponse_()
    : out()  {
    }
  simple_srvResponse_(const ContainerAllocator& _alloc)
    : out(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _out_type;
  _out_type out;





  typedef boost::shared_ptr< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simple_srvResponse_

typedef ::demo_service_cpp::simple_srvResponse_<std::allocator<void> > simple_srvResponse;

typedef boost::shared_ptr< ::demo_service_cpp::simple_srvResponse > simple_srvResponsePtr;
typedef boost::shared_ptr< ::demo_service_cpp::simple_srvResponse const> simple_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo_service_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da0977a72deba269ef1a5e91941513be";
  }

  static const char* value(const ::demo_service_cpp::simple_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda0977a72deba269ULL;
  static const uint64_t static_value2 = 0xef1a5e91941513beULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_service_cpp/simple_srvResponse";
  }

  static const char* value(const ::demo_service_cpp::simple_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string out\n\
";
  }

  static const char* value(const ::demo_service_cpp::simple_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_service_cpp::simple_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_service_cpp::simple_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "out: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRVRESPONSE_H
