// Generated by gencpp from file demo_service_cpp/simple_srv.msg
// DO NOT EDIT!


#ifndef DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRV_H
#define DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRV_H

#include <ros/service_traits.h>


#include <demo_service_cpp/simple_srvRequest.h>
#include <demo_service_cpp/simple_srvResponse.h>


namespace demo_service_cpp
{

struct simple_srv
{

typedef simple_srvRequest Request;
typedef simple_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simple_srv
} // namespace demo_service_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_service_cpp::simple_srv > {
  static const char* value()
  {
    return "e21fb7853ad73d6d988d6371d4fed1e2";
  }

  static const char* value(const ::demo_service_cpp::simple_srv&) { return value(); }
};

template<>
struct DataType< ::demo_service_cpp::simple_srv > {
  static const char* value()
  {
    return "demo_service_cpp/simple_srv";
  }

  static const char* value(const ::demo_service_cpp::simple_srv&) { return value(); }
};


// service_traits::MD5Sum< ::demo_service_cpp::simple_srvRequest> should match 
// service_traits::MD5Sum< ::demo_service_cpp::simple_srv > 
template<>
struct MD5Sum< ::demo_service_cpp::simple_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_service_cpp::simple_srv >::value();
  }
  static const char* value(const ::demo_service_cpp::simple_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_service_cpp::simple_srvRequest> should match 
// service_traits::DataType< ::demo_service_cpp::simple_srv > 
template<>
struct DataType< ::demo_service_cpp::simple_srvRequest>
{
  static const char* value()
  {
    return DataType< ::demo_service_cpp::simple_srv >::value();
  }
  static const char* value(const ::demo_service_cpp::simple_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_service_cpp::simple_srvResponse> should match 
// service_traits::MD5Sum< ::demo_service_cpp::simple_srv > 
template<>
struct MD5Sum< ::demo_service_cpp::simple_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_service_cpp::simple_srv >::value();
  }
  static const char* value(const ::demo_service_cpp::simple_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_service_cpp::simple_srvResponse> should match 
// service_traits::DataType< ::demo_service_cpp::simple_srv > 
template<>
struct DataType< ::demo_service_cpp::simple_srvResponse>
{
  static const char* value()
  {
    return DataType< ::demo_service_cpp::simple_srv >::value();
  }
  static const char* value(const ::demo_service_cpp::simple_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_SERVICE_CPP_MESSAGE_SIMPLE_SRV_H
