; Auto-generated. Do not edit!


(cl:in-package demo_action_python-msg)


;//! \htmlinclude python_actionFeedback.msg.html

(cl:defclass <python_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((current_number
    :reader current_number
    :initarg :current_number
    :type cl:integer
    :initform 0))
)

(cl:defclass python_actionFeedback (<python_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <python_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'python_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name demo_action_python-msg:<python_actionFeedback> is deprecated: use demo_action_python-msg:python_actionFeedback instead.")))

(cl:ensure-generic-function 'current_number-val :lambda-list '(m))
(cl:defmethod current_number-val ((m <python_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader demo_action_python-msg:current_number-val is deprecated.  Use demo_action_python-msg:current_number instead.")
  (current_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <python_actionFeedback>) ostream)
  "Serializes a message object of type '<python_actionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <python_actionFeedback>) istream)
  "Deserializes a message object of type '<python_actionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<python_actionFeedback>)))
  "Returns string type for a message object of type '<python_actionFeedback>"
  "demo_action_python/python_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'python_actionFeedback)))
  "Returns string type for a message object of type 'python_actionFeedback"
  "demo_action_python/python_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<python_actionFeedback>)))
  "Returns md5sum for a message object of type '<python_actionFeedback>"
  "a34d09927bdf6eea84e4ff079b190b1d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'python_actionFeedback)))
  "Returns md5sum for a message object of type 'python_actionFeedback"
  "a34d09927bdf6eea84e4ff079b190b1d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<python_actionFeedback>)))
  "Returns full string definition for message of type '<python_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'python_actionFeedback)))
  "Returns full string definition for message of type 'python_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <python_actionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <python_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'python_actionFeedback
    (cl:cons ':current_number (current_number msg))
))
