// Generated by gencpp from file demo_action_cpp/demo_actionResult.msg
// DO NOT EDIT!


#ifndef DEMO_ACTION_CPP_MESSAGE_DEMO_ACTIONRESULT_H
#define DEMO_ACTION_CPP_MESSAGE_DEMO_ACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_action_cpp
{
template <class ContainerAllocator>
struct demo_actionResult_
{
  typedef demo_actionResult_<ContainerAllocator> Type;

  demo_actionResult_()
    : final_count(0)  {
    }
  demo_actionResult_(const ContainerAllocator& _alloc)
    : final_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _final_count_type;
  _final_count_type final_count;





  typedef boost::shared_ptr< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct demo_actionResult_

typedef ::demo_action_cpp::demo_actionResult_<std::allocator<void> > demo_actionResult;

typedef boost::shared_ptr< ::demo_action_cpp::demo_actionResult > demo_actionResultPtr;
typedef boost::shared_ptr< ::demo_action_cpp::demo_actionResult const> demo_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_action_cpp::demo_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo_action_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'demo_action_cpp': ['/home/ammmy/Desktop/tutorial_ws/devel/share/demo_action_cpp/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaae876f57686d9f2a92f60bfbd26c85";
  }

  static const char* value(const ::demo_action_cpp::demo_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaae876f57686d9fULL;
  static const uint64_t static_value2 = 0x2a92f60bfbd26c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_action_cpp/demo_actionResult";
  }

  static const char* value(const ::demo_action_cpp::demo_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 final_count\n\
";
  }

  static const char* value(const ::demo_action_cpp::demo_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demo_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_action_cpp::demo_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_action_cpp::demo_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "final_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.final_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_ACTION_CPP_MESSAGE_DEMO_ACTIONRESULT_H
