// Generated by gencpp from file demo_action_cpp/demo_actionGoal.msg
// DO NOT EDIT!


#ifndef DEMO_ACTION_CPP_MESSAGE_DEMO_ACTIONGOAL_H
#define DEMO_ACTION_CPP_MESSAGE_DEMO_ACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_action_cpp
{
template <class ContainerAllocator>
struct demo_actionGoal_
{
  typedef demo_actionGoal_<ContainerAllocator> Type;

  demo_actionGoal_()
    : count(0)  {
    }
  demo_actionGoal_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct demo_actionGoal_

typedef ::demo_action_cpp::demo_actionGoal_<std::allocator<void> > demo_actionGoal;

typedef boost::shared_ptr< ::demo_action_cpp::demo_actionGoal > demo_actionGoalPtr;
typedef boost::shared_ptr< ::demo_action_cpp::demo_actionGoal const> demo_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo_action_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'demo_action_cpp': ['/home/ammmy/Desktop/tutorial_ws/devel/share/demo_action_cpp/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::demo_action_cpp::demo_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_action_cpp/demo_actionGoal";
  }

  static const char* value(const ::demo_action_cpp::demo_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 count\n\
";
  }

  static const char* value(const ::demo_action_cpp::demo_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demo_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_action_cpp::demo_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_action_cpp::demo_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_ACTION_CPP_MESSAGE_DEMO_ACTIONGOAL_H
