// Generated by gencpp from file demo_service_python/python_srv.msg
// DO NOT EDIT!


#ifndef DEMO_SERVICE_PYTHON_MESSAGE_PYTHON_SRV_H
#define DEMO_SERVICE_PYTHON_MESSAGE_PYTHON_SRV_H

#include <ros/service_traits.h>


#include <demo_service_python/python_srvRequest.h>
#include <demo_service_python/python_srvResponse.h>


namespace demo_service_python
{

struct python_srv
{

typedef python_srvRequest Request;
typedef python_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct python_srv
} // namespace demo_service_python


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_service_python::python_srv > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::demo_service_python::python_srv&) { return value(); }
};

template<>
struct DataType< ::demo_service_python::python_srv > {
  static const char* value()
  {
    return "demo_service_python/python_srv";
  }

  static const char* value(const ::demo_service_python::python_srv&) { return value(); }
};


// service_traits::MD5Sum< ::demo_service_python::python_srvRequest> should match 
// service_traits::MD5Sum< ::demo_service_python::python_srv > 
template<>
struct MD5Sum< ::demo_service_python::python_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_service_python::python_srv >::value();
  }
  static const char* value(const ::demo_service_python::python_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_service_python::python_srvRequest> should match 
// service_traits::DataType< ::demo_service_python::python_srv > 
template<>
struct DataType< ::demo_service_python::python_srvRequest>
{
  static const char* value()
  {
    return DataType< ::demo_service_python::python_srv >::value();
  }
  static const char* value(const ::demo_service_python::python_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_service_python::python_srvResponse> should match 
// service_traits::MD5Sum< ::demo_service_python::python_srv > 
template<>
struct MD5Sum< ::demo_service_python::python_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_service_python::python_srv >::value();
  }
  static const char* value(const ::demo_service_python::python_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_service_python::python_srvResponse> should match 
// service_traits::DataType< ::demo_service_python::python_srv > 
template<>
struct DataType< ::demo_service_python::python_srvResponse>
{
  static const char* value()
  {
    return DataType< ::demo_service_python::python_srv >::value();
  }
  static const char* value(const ::demo_service_python::python_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_SERVICE_PYTHON_MESSAGE_PYTHON_SRV_H
