// Generated by gencpp from file demo_service_python/python_srvResponse.msg
// DO NOT EDIT!


#ifndef DEMO_SERVICE_PYTHON_MESSAGE_PYTHON_SRVRESPONSE_H
#define DEMO_SERVICE_PYTHON_MESSAGE_PYTHON_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_service_python
{
template <class ContainerAllocator>
struct python_srvResponse_
{
  typedef python_srvResponse_<ContainerAllocator> Type;

  python_srvResponse_()
    : sum(0)  {
    }
  python_srvResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::demo_service_python::python_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_service_python::python_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct python_srvResponse_

typedef ::demo_service_python::python_srvResponse_<std::allocator<void> > python_srvResponse;

typedef boost::shared_ptr< ::demo_service_python::python_srvResponse > python_srvResponsePtr;
typedef boost::shared_ptr< ::demo_service_python::python_srvResponse const> python_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_service_python::python_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_service_python::python_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo_service_python

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_service_python::python_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_service_python::python_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_service_python::python_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::demo_service_python::python_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_service_python/python_srvResponse";
  }

  static const char* value(const ::demo_service_python::python_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n\
";
  }

  static const char* value(const ::demo_service_python::python_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct python_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_service_python::python_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_service_python::python_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_SERVICE_PYTHON_MESSAGE_PYTHON_SRVRESPONSE_H
