(cl:defpackage demo_action_cpp-msg
  (:use )
  (:export
   "<DEMO_ACTIONACTION>"
   "DEMO_ACTIONACTION"
   "<DEMO_ACTIONACTIONFEEDBACK>"
   "DEMO_ACTIONACTIONFEEDBACK"
   "<DEMO_ACTIONACTIONGOAL>"
   "DEMO_ACTIONACTIONGOAL"
   "<DEMO_ACTIONACTIONRESULT>"
   "DEMO_ACTIONACTIONRESULT"
   "<DEMO_ACTIONFEEDBACK>"
   "DEMO_ACTIONFEEDBACK"
   "<DEMO_ACTIONGOAL>"
   "DEMO_ACTIONGOAL"
   "<DEMO_ACTIONRESULT>"
   "DEMO_ACTIONRESULT"
  ))

